### ISSUE TITLE
Push instead of poll when graph changes

### ISSUE THREAD

**Issue by fredleb** [OLSR/OONF#38]
To get graph updates I regularly poll the netjson info plugin via http or telnet, which artificially increases traffic with all its consequences... Is there any way to configure OLSR to send a signal any time it detects a graph change ? I would like to move a away from polling to something more event triggered.

**Comment by HRogge** [comment]
No, there is not...

in addition to the limitations of the OLSR HTTP code, there is the problem that the graph contains ALL metrics... which means it always changes because of the probabilistic measurement of the packet loss.

As long as you measure it on your local node, this traffic should flow with "Loopback" or at least with Ethernet speed... which should make querying it 1/second (or something similar) not a problem.

if you really need to collect the data in a more efficient way, maybe a local daemon that queries OLSR, compress the data (and strip it of redundancies) and then send it to you might be an option?

**Comment by fredleb** [comment]
The local daemon polling and making some early low-pass filtering + decisions is already what we have deployed.

It works fine in a lab but what about a portable setup with a limited battery life ? Even 1Hz might become a heavy burden in the long run, especially for systems that will see little to no change in hours or days…

I understand that it mathematically always changes but transient 1kbps fluctuations around a 1Mbps mean is not the kind of information that is worth propagating vs battery life. Is such a thing feasible as a plugin ?

**Comment by HRogge** [comment]
you can build anything you want into an OONF plugin... but I don't think it would be more energy efficient then just a loopback query.

the problem is that the TC database will change every times a HELLO or a TC is incoming... which means you get LOTS of changes.

So maybe a plugin which implements your lowpass-filter might be the way for you.
