### ISSUE TITLE
Dynamic plugin loading seems broken

### ISSUE THREAD

**Issue by jpo-github-work** [OLSR/OONF#50]
I'm unsure about this, because it seems like a very fundamental functionality. It's hard to imagine that this is broken and nobody noticed until now, but here we go. I'm using the simplest configuration that can reproduce the issue:
```
[global]
	plugin lan_import

[log]
	debug plugins
```
Calling the program:
```
[olsr@fedora ~]$ sudo /usr/local/sbin/olsrd2_dynamic -l load-plugin.conf 
19:21:44.448 DEBUG(plugins) src/libcore/oonf_subsystem.c 514: dlopen (/liboonf_lan_import.so.0.15.1,0x1) failed: /liboonf_lan_import.so.0.15.1: cannot open shared object file: No such file or directory
19:21:44.448 DEBUG(plugins) src/libcore/oonf_subsystem.c 514: dlopen (/liboonf_lan_import.so,0x1) failed: /liboonf_lan_import.so: cannot open shared object file: No such file or directory
19:21:44.450 INFO(plugins) src/libcore/oonf_subsystem.c 517: dlopen (liboonf_lan_import.so.0.15.1,0x1) succeeded
19:21:44.450 WARN(plugins) src/libcore/oonf_subsystem.c 312: dynamic library loading failed: "(null)"!
```
The log statement `WARN(plugins) src/libcore/oonf_subsystem.c 312: dynamic library loading failed: "(null)"!` comes from function [oonf_subsystem_load(const char *libname)](https://github.com/OLSR/OONF/blob/fb15d54d6a7a087cb0c5ec37c49804f6ce432396/src/libcore/oonf_subsystem.c#L295):

```
struct oonf_subsystem *
oonf_subsystem_load(const char *libname) {
  struct oonf_subsystem *plugin;
  void *dlhandle;
  int idx;

  /* see if the plugin is there */
  if ((plugin = oonf_subsystem_get(libname)) == NULL) {
    /* attempt to load the plugin */
    dlhandle = _open_plugin(libname, &idx);

    if (dlhandle == NULL) {
      /* Logging output has already been done by _open_plugin() */
      return NULL;
    }

    /* plugin should be in the tree now */
    if ((plugin = oonf_subsystem_get(libname)) == NULL) {
      OONF_WARN(LOG_PLUGINS, "dynamic library loading failed: \"%s\"!\n", dlerror());
      dlclose(dlhandle);
      return NULL;
    }

    plugin->_dlhandle = dlhandle;
    plugin->_dlpath_index = idx;
  }
  return plugin;
}
```
The code tries to load the plugin, if it hasn't previously been loaded, e.g. if `oonf_subsystem_get` returns NULL. `_open_plugin` seems to be just a fancy wrapper around `dlopen`. I can't see code between `_open_plugin` in line [303](https://github.com/OLSR/OONF/blob/fb15d54d6a7a087cb0c5ec37c49804f6ce432396/src/libcore/oonf_subsystem.c#L303) and the second call to `oonf_subsystem_get` in line [311](https://github.com/OLSR/OONF/blob/fb15d54d6a7a087cb0c5ec37c49804f6ce432396/src/libcore/oonf_subsystem.c#L311) that would register the plugin. So the comment `/* plugin should be in the tree now */` doesn't match reality and we get the warning in line [312](https://github.com/OLSR/OONF/blob/fb15d54d6a7a087cb0c5ec37c49804f6ce432396/src/libcore/oonf_subsystem.c#L312).

**Comment by HRogge** [comment]
Yes you are right, there is no code between the "dlopen()" and the "should be in the tree"... thats because every plugin has a "constructor" section, which is run by the lunker when the plugin is loaded (either statically or dynamically). It was the only way I found to call code within the plugin easily AND use the same codepath for static loading.

See:
https://github.com/OLSR/OONF/blob/master/include/oonf/libcore/oonf_subsystem.h#L66

**Comment by jpo-github-work** [comment]
Henning, that was indeed helpful I think I found the issue:

- src/olsrv2/lan_import/lan_import.c Line [211](https://github.com/OLSR/OONF/blob/fb15d54d6a7a087cb0c5ec37c49804f6ce432396/src/olsrv2/lan_import/lan_import.c#L211): `DECLARE_OONF_PLUGIN(_import_subsystem);`
- src/generic/layer2_import/layer2_import.c Line [234](https://github.com/OLSR/OONF/blob/fb15d54d6a7a087cb0c5ec37c49804f6ce432396/src/generic/layer2_import/layer2_import.c#L234): `DECLARE_OONF_PLUGIN(_import_subsystem);`

Both expand to the same symbol and the wrong one gets called.

**Comment by HRogge** [comment]
There are two plugins defining the same capability (lan import).

So there is no bug, you should still have "lan_import" configuration options when working with the layer2_import plugin.

This happened because I needed that "lan_import" data also in the OONF internal layer2 database... so I wrote a new plugin that imports it there and added a second plugin that automatically moves entries based on the name of the source from the layer-2 database to the OLSRv2 LAN database.

If you have layer2_import and olsrv2_l2import plugins, you should have a working "lan_import" config option... without the lan_import plugin.

**Comment by jpo-github-work** [comment]
Well, something is broken, I'm now just unsure what exactly. As I understand you, the original lan_import plugin is has been superceded by the layer2_import plugin, correct? That means:

- Commit 8cc65a10651d12b0ee5187c6ce397e34ad157d8b should be reverted
- And maybe the Wiki page [LAN Import Plugin](http://www.olsr.org/mediawiki/index.php/LAN_Import_Plugin) should mention that...

**Comment by jpo-github-work** [comment]
Plugin loading works as designed. The root problem has been identified and should be discussed in issue  #47.
